# OpenAI API Key
openai_api_key = "your_openai_api_key_here"
openai_organization = "your_openai_org_id_here"

# OpenAI Model
openai_model = "gpt-4o"

# Openrouter configuration
openrouter_api_key = "your_openrouter_api_key_here"
openrouter_api_base = "https://openrouter.ai/api/v1"

# Openrouter model configuration
# Default model
openrouter_model = "mistralai/mistral-small-3.1-24b-instruct"

# Available models for selection
openrouter_model_mistral = "mistralai/mistral-small-3.1-24b-instruct"
openrouter_model_qwen = "qwen/qwen2.5-vl-32b-instruct:free"
openrouter_model_gemma = "google/gemma-3-27b-it"

# PostgreSQL Connection String
postgres_connection_string = "postgresql://username:password@host:port/database"
